### ISSUE TITLE
Kernel panic (intermittent) and reboot

### ISSUE THREAD

**Issue by mszoek** [ravynsoft/ravynos#221]
Since rebasing to FreeBSD `stable/13` I have seen a few spontaneous reboots on my 0.4.0 dev VM. The crash dumps are usually similar to this backtrace:

```
(kgdb) bt
#0  sched_switch (td=td@entry=0xffffffff8216ba00 <thread0_st>, flags=<optimized out>, 
    flags@entry=260) at /usr/src/sys/kern/sched_ule.c:2225
#1  0xffffffff80de85d7 in mi_switch (flags=flags@entry=260)
    at /usr/src/sys/kern/kern_synch.c:549
#2  0xffffffff80e3bfbe in sleepq_switch (wchan=wchan@entry=0xffffffff8216b468 <proc0>, 
    pri=pri@entry=84) at /usr/src/sys/kern/subr_sleepqueue.c:608
#3  0xffffffff80e3c5ff in sleepq_timedwait (wchan=<unavailable>, 
    wchan@entry=0xffffffff8216b468 <proc0>, pri=<unavailable>)
    at /usr/src/sys/kern/subr_sleepqueue.c:690
#4  0xffffffff80de7cbb in _sleep (ident=0xffffffff8216b468 <proc0>, 
    lock=<optimized out>, lock@entry=0x0, priority=priority@entry=84, 
    wmesg=0xffffffff814e6cbc "swapin", sbt=42949672000, pr=<optimized out>, pr@entry=0, 
    flags=256) at /usr/src/sys/kern/kern_synch.c:220
#5  0xffffffff8113ef69 in swapper () at /usr/src/sys/vm/vm_swapout.c:752
#6  0xffffffff803b2022 in btext () at /usr/src/sys/amd64/amd64/locore.S:80
```

There are also frequent messages of `kernel trap 12 with interrupts disabled` in `dmesg`.

```
uhub1: 6 ports with 6 removable, self powered
uhub2: 7 ports with 7 removable, self powered
ugen1.2: <VMware, Inc. VMware Virtual USB Video Device> at usbus1
kernel trap 12 with interrupts disabled
kernel trap 12 with interrupts disabled
kernel trap 12 with interrupts disabled
kernel trap 12 with interrupts disabled
kernel trap 12 with interrupts disabled
intsmb0: <Intel PIIX4 SMBUS Interface> port 0x1040-0x104f at device 7.3 on pci0
intsmb0: intr SMI disabled revision 0
smbus0: <System Management Bus> on intsmb0
```

**Comment by mszoek** [comment]
Haven't seen these in a while now.
