### ISSUE TITLE
Potential deadlock in thr_workq?

### ISSUE THREAD

**Issue by mszoek** [ravynsoft/ravynos#287]
System froze and eventually panicked while in GUI mode. The crash dump backtrace appears to be a mutex held too long from `twq_run_nextitem`. The process was `asld`.

```
(kgdb) bt
#0  __curthread () at /usr/src/sys/amd64/include/pcpu_aux.h:59
#1  dump_savectx () at /usr/src/sys/kern/kern_shutdown.c:401
#2  0xffffffff80be9c58 in dumpsys (di=0x0) at /usr/src/sys/x86/include/dump.h:87
#3  doadump (textdump=1) at /usr/src/sys/kern/kern_shutdown.c:430
#4  kern_reboot (howto=260) at /usr/src/sys/kern/kern_shutdown.c:537
#5  0xffffffff80bea13e in vpanic (fmt=<optimized out>, ap=ap@entry=0xfffffe015c4edab0) at /usr/src/sys/kern/kern_shutdown.c:975
#6  0xffffffff80be9f73 in panic (fmt=<unavailable>) at /usr/src/sys/kern/kern_shutdown.c:899
#7  0xffffffff80bc6ee8 in _mtx_lock_indefinite_check (m=<optimized out>, ldap=<optimized out>)
    at /usr/src/sys/kern/kern_mutex.c:1261
#8  0xffffffff80bc703b in thread_lock_flags_ (td=0xfffff801d7d8a740, opts=<optimized out>, file=<optimized out>, 
    line=<optimized out>) at /usr/src/sys/kern/kern_mutex.c:930
#9  0xffffffff80b77487 in statclock (cnt=1, usermode=usermode@entry=0) at /usr/src/sys/kern/kern_clock.c:700
#10 0xffffffff80b77e53 in handleevents (now=now@entry=14801436182096, fake=fake@entry=0) at /usr/src/sys/kern/kern_clocksource.c:196
#11 0xffffffff80b78b6e in timercb (et=0xffffffff81d53088 <lapic_et>, arg=<optimized out>)
    at /usr/src/sys/kern/kern_clocksource.c:358
#12 0xffffffff811694c6 in lapic_handle_timer (frame=<optimized out>) at /usr/src/sys/x86/x86/local_apic.c:1339
#13 <signal handler called>
#14 _thread_lock (td=0xfffff801d7d8a740) at /usr/src/sys/kern/kern_mutex.c:846
#15 0xffffffff80c04743 in twq_run_nextitem (p=0xfffffe0112f20680, wq=0xfffffe01442c9000, thread=0xfffff801d7d8a740, 
    oc_item=<optimized out>, oc_prio=<optimized out>, oc_affinity=oc_affinity@entry=-1) at /usr/src/sys/kern/kern_thrworkq.c:1765
#16 0xffffffff80c0554d in sys_thr_workq (td=<optimized out>, uap=<optimized out>) at /usr/src/sys/kern/kern_thrworkq.c:1119
#17 0xffffffff810a16e4 in syscallenter (td=0xfffff801d7d8a740) at /usr/src/sys/amd64/amd64/../../kern/subr_syscall.c:161
#18 amd64_syscall (td=0xfffff801d7d8a740, traced=0) at /usr/src/sys/amd64/amd64/trap.c:1187
#19 <signal handler called>
#20 0x000023da79ca903a in ?? ()
```

```
#7  0xffffffff80bc6ee8 in _mtx_lock_indefinite_check (m=<optimized out>, ldap=<optimized out>)
    at /usr/src/sys/kern/kern_mutex.c:1261
1261                    panic("spin lock held too long");
```

```
#8  0xffffffff80bc703b in thread_lock_flags_ (td=0xfffff801d7d8a740, opts=<optimized out>, file=<optimized out>, 
    line=<optimized out>) at /usr/src/sys/kern/kern_mutex.c:930
930                                             _mtx_lock_indefinite_check(m, &lda);
(kgdb) p m
$1 = (struct mtx *) 0xffffffff82abe0c0
(kgdb) p *m
$2 = {lock_object = {lo_name = 0xffffffff82abed40 "sched lock 0", lo_flags = 196608, lo_data = 0, lo_witness = 0x0}, 
  mtx_lock = 18446735285532796736}
(kgdb) p lda
$3 = {config = 0xffffffff81801018 <locks_delay>, delay = 4096, spin_cnt = 60000000}
```

Called from here:

```
#15 0xffffffff80c04743 in twq_run_nextitem (p=0xfffffe0112f20680, wq=0xfffffe01442c9000, thread=0xfffff801d7d8a740,          
    oc_item=<optimized out>, oc_prio=<optimized out>, oc_affinity=oc_affinity@entry=-1) at /usr/src/sys/kern/kern_thrworkq.c:1765
1765            thread_lock(th_to_park);                                                                                             
(kgdb) list                                                                                                                          
1760            tl->th_flags &= ~TH_LIST_RUNNING;                                                                                    
1761                                                                                                                                 
1762            tl->th_flags |= TH_LIST_BLOCKED;                                                                                     
1763            TAILQ_INSERT_HEAD(&wq->wq_thidlelist, tl, th_entry);                                                             
1764                                                                                                                                 
1765            thread_lock(th_to_park);                                                                                             
1766            twq_set_schedcallback(th_to_park, NULL);                                                                             
1767            thread_unlock(th_to_park);                                                                                           
1768
1769            atomic_add_32(&wq->wq_thactive_count[tl->th_priority]

#16 0xffffffff80c0554d in sys_thr_workq (td=<optimized out>, uap=<optimized out>) at /usr/src/sys/kern/kern_thrworkq.c:1119
1119                    (void)twq_run_nextitem(p, wq, NULL, oc_item, prio, affinity);
```

**Comment by mszoek** [comment]
Have not seen this in a while... Leaving the issue open a while longer to monitor.

**Comment by mszoek** [comment]
Closing as not reproducible anymore.
